"""
embedder.py - Task 2.3: Embedding & Vector Storage

This script reads the semantically structured chunks generated by chunker.py,
generates dense vector embeddings using BAAI/bge-small-en-v1.5, and stores
them into a local ChromaDB instance for later RAG retrieval.
"""

import os
import json
import chromadb
from chromadb.utils import embedding_functions

PROCESSED_DATA_DIR = "./data/processed"
INPUT_FILE = os.path.join(PROCESSED_DATA_DIR, "chunks.json")
CHROMA_DB_DIR = "./chroma_db/"
COLLECTION_NAME = "groww_mutual_funds"
EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"

def get_embedder():
    """Returns the SentenceTransformer embedding function for ChromaDB."""
    print(f"Loading embedding model: {EMBEDDING_MODEL} (this may take a moment to download on first run)...")
    return embedding_functions.SentenceTransformerEmbeddingFunction(model_name=EMBEDDING_MODEL)

def process_and_store():
    # 1. Load the chunks
    if not os.path.exists(INPUT_FILE):
        print(f"Error: Input file {INPUT_FILE} not found. Please run chunker.py first.")
        return
        
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        chunks = json.load(f)
        
    print(f"Loaded {len(chunks)} chunks from {INPUT_FILE}")

    if not chunks:
        print("No chunks to process.")
        return

    # 2. Initialize ChromaDB
    print(f"Initializing local ChromaDB at {CHROMA_DB_DIR}...")
    chroma_client = chromadb.PersistentClient(path=CHROMA_DB_DIR)
    
    embedder = get_embedder()
    
    # Get or create collection
    # Note: We recreate or get. Since we might run this multiple times during dev,
    # let's try to get or create. If we want a clean slate, we can delete the collection first.
    try:
        chroma_client.delete_collection(name=COLLECTION_NAME)
        print(f"Deleted existing collection '{COLLECTION_NAME}' for a clean slate.")
    except Exception:
        pass
        
    collection = chroma_client.create_collection(
        name=COLLECTION_NAME,
        embedding_function=embedder,
        metadata={"description": "Groww Mutual Funds FAQ and Factsheets"}
    )
    
    # 3. Prepare data for ChromaDB
    documents = []
    metadatas = []
    ids = []
    
    for i, chunk in enumerate(chunks):
        documents.append(chunk['text'])
        
        # Ensure all metadata values are strings, ints, floats, or bools as required by ChromaDB
        # We also want to provide default values if some keys are missing
        meta = chunk.get('metadata', {})
        clean_meta = {
            "source": str(meta.get('source', '')),
            "section": str(meta.get('section', 'unknown')),
            "amc_name": str(meta.get('amc_name', 'Unknown')),
        }
        if 'fund_name' in meta:
            clean_meta['fund_name'] = str(meta['fund_name'])
            
        metadatas.append(clean_meta)
        
        # Create a unique ID for each chunk based on index
        # Alternatively, we could hash the content, but an index is fine for our controlled pipeline.
        chunk_id = f"chunk_{i}"
        ids.append(chunk_id)

    # 4. Add to vector store
    print(f"Embedding and storing {len(documents)} chunks in ChromaDB...")
    
    # ChromaDB processes embeddings in batches implicitly, but we can just add them all if it's small.
    # 181 chunks is very small, we can add them in one go.
    collection.add(
        documents=documents,
        metadatas=metadatas,
        ids=ids
    )
    
    print(f"\nSuccessfully stored {len(documents)} vectors in collection '{COLLECTION_NAME}'!")
    print(f"Vector Database is ready at: {CHROMA_DB_DIR}")

if __name__ == "__main__":
    process_and_store()
